apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dha6l6wc6-python 
  janus-idp.io/tekton: dha6l6wc6-python
  backstage.io/kubernetes-id: dha6l6wc6-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dha6l6wc6-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml